# Usa una imagen base que contenga el servidor web y el lenguaje de programación que necesitas (por ejemplo, PHP, Python, Node.js)
FROM php:7.4-apache

# Copia los archivos de tu aplicación al directorio de trabajo dentro del contenedor
COPY . /var/www/html/
