version: "3.1"
services:
    db:
        image: mongo
        ports: 
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
            - mongodb_data:/data/db
            - persistent:/var/lib/mongo
        networks:
            - mynetwork

    
    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_SITE_COOKIESECRET: admin
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
    persistent:
    mongodb_data:

